[package]
name = "xml_to_excel"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.40", features = ["lazy"] }
quick-xml = { version = "0.31", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
glob = "0.3"
rust_xlsxwriter = "0.67"
anyhow = "1.0"
