[package]
name = "schedulebot"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.40", features = ["lazy"] }
quick-xml = { version = "0.31", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
glob = "0.3"
rust_xlsxwriter = "0.67"
anyhow = "1.0"
indexmap = "2.9.0"
struct-field-names-as-array = "0.3.0"
uuid = "1.17.0"
zip-extract = "0.4.0"
tempfile = "3.20.0"
