[package]
name = "schedulebot"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1

[dependencies]
polars = { version = "^0.49.1", features = ["lazy"] }
quick-xml = { version = "^0.37.5", features = ["serialize"] }
serde = { version = "^1.0.219", features = ["derive"] }
glob = "^0.3.2"
rust_xlsxwriter = "^0.88.0"
anyhow = "^1.0.98"
indexmap = "^2.9.0"
struct-field-names-as-array = "^0.3.0"
uuid = "^1.17.0"
tempfile = "^3.20.0"
rc-zip-sync = "^4.3.0"
calamine = "^0.28.0"
strum = "^0.27.1"
strum_macros = "^0.27.1"
num_enum = "^0.7.4"
ouroboros = "0.18.5"
