channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.*
  - requests=2.32.*
  - bs4=4.12.*
  - requests-cache=1.2.*
  - pandas=2.2.*
  - openpyxl=3.1.*
  - pathvalidate=3.3.*
  - lxml=5.3.*
