[package]
name = "rust_cpsat"
version = "0.1.0"
edition = "2024"

[dependencies]
cp_sat = { git = "https://github.com/bc-ross/cp_sat.git", rev = "2ba15818232d73fb5169fc806f57b7c96aed8bcb" }
anyhow = "^1.0.98"
